/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RunasUserAuth struct {
	// control-M server name
	ControlmServer string `json:"ControlmServer,omitempty"`
	// runas user
	RunasUser string `json:"RunasUser,omitempty"`
	// HOst or host group value
	Host string `json:"Host,omitempty"`
}
