/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ServiceProviderInformation struct {
	SingleSignOnUrl string `json:"singleSignOnUrl,omitempty"`
	EntityID string `json:"entityID,omitempty"`
	SigningCertificate string `json:"signingCertificate,omitempty"`
}
