/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// File Transfer Server LDAP authentication parameters
type FtsLdapAuthenticationDetails struct {
	// Name of the user that runs the search action for users that log on
	SearchUserName string `json:"searchUserName,omitempty"`
	// Password of the user that runs the search action for users that log on
	SearchUserPassword string `json:"searchUserPassword,omitempty"`
	// URL of the LDAP Directory server
	ServerUrl string `json:"serverUrl,omitempty"`
	// Base DN (the point from where the server will search for users)
	BaseDn string `json:"baseDn,omitempty"`
	// Name of the LDAP attribute containing the username
	UsernameAttributeName string `json:"usernameAttributeName,omitempty"`
	// Name of the LDAP attribute containing the distinguished name
	DnAttributeName string `json:"dnAttributeName,omitempty"`
	// LDAP server connection timeout in milliseconds
	ConnectionTimeout int32 `json:"connectionTimeout,omitempty"`
}
