/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// Specifications of an agent
type JobtypeAgent struct {
	// Server name
	Server string `json:"server,omitempty"`
	// Agent name
	Agent string `json:"agent,omitempty"`
}
