/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ConfigurationManagerPrivilegeCategory struct {
	// Authorization access level (None, Browse, Update, Full)
	Authorization string `json:"Authorization,omitempty"`
	// Control-M Configuration Manager access level (None, Full)
	ConfigurationManagerAccess string `json:"ConfigurationManagerAccess,omitempty"`
	// Configuration access level (None, Browse, Update, Full)
	Configuration string `json:"Configuration,omitempty"`
	// Operation access level (None, Browse, Update, Full)
	Operation string `json:"Operation,omitempty"`
	// Database Maintenance access level (None, Browse, Update, Full)
	Database string `json:"Database,omitempty"`
	// Security access level (None, Browse, Update, Full)
	ControlmSecurity string `json:"ControlmSecurity,omitempty"`
}
