/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RerunZosParameters struct {
	From *RestartStep `json:"from,omitempty"`
	To *RestartStep `json:"to,omitempty"`
	// cleanup instead of running specific steps. HIDDEN.
	Cleanup bool `json:"cleanup,omitempty"`
	// TO BE ADDED. HIDDEN.
	RecaptureAbend string `json:"recaptureAbend,omitempty"`
	// TO BE ADDED. HIDDEN.
	RecaptureConditionCode string `json:"recaptureConditionCode,omitempty"`
	// TO BE ADDED. HIDDEN.
	StepAdjustment bool `json:"stepAdjustment,omitempty"`
	// TO BE ADDED. HIDDEN.
	RestartParmMemberName string `json:"restartParmMemberName,omitempty"`
}
