/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// AI standard error object
type AiError struct {
	// Error message
	Message string `json:"message,omitempty"`
	// Http status code
	Status int32 `json:"status,omitempty"`
}
