/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type SettingsUpdateObject struct {
	SettingsObj *SettingPropertiesObject `json:"SettingsObj,omitempty"`
	CompKeyType *ComponentMftKeyType `json:"CompKeyType,omitempty"`
}
