/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type FoldersUsersSettingsAndMetadataPropertiesFromB2B struct {
	Folders []FolderProperties `json:"folders,omitempty"`
	Settings []SettingProperties `json:"settings,omitempty"`
	SettingsMetadata *SettingsMetadataProperties `json:"settingsMetadata,omitempty"`
	Users []UserAllowedFoldersProperties `json:"users,omitempty"`
	Groups []GroupsAllowedFoldersProperties `json:"groups,omitempty"`
}
