/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ServiceAuth struct {
	// access level (Full, Update, Browse, None)
	Privilege string `json:"Privilege,omitempty"`
	// service name
	Name string `json:"Name,omitempty"`
	AllowedActions *ServiceAuthAction `json:"AllowedActions,omitempty"`
}
