/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type AddRemoveSuccessData struct {
	// The success message that describes the performed action.
	Message string `json:"message,omitempty"`
	// List of the items remained after the action.
	CurrentItems []string `json:"currentItems,omitempty"`
}
