/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RunReportInfo struct {
	ReportId string `json:"reportId,omitempty"`
	Name string `json:"name,omitempty"`
	Format string `json:"format,omitempty"`
	Status string `json:"status,omitempty"`
	Url string `json:"url,omitempty"`
	WebUrl string `json:"webUrl,omitempty"`
}
