/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type UpgradeRecord struct {
	// upgrade id
	UpgradeId string `json:"upgradeId,omitempty"`
	// Control-M name
	Ctm string `json:"ctm,omitempty"`
	// agnet name
	Agent string `json:"agent,omitempty"`
	// upgrade package type
	Package_ string `json:"package,omitempty"`
	// upgrade from version
	FromVersion string `json:"fromVersion,omitempty"`
	// upgrade to version
	ToVersion string `json:"toVersion,omitempty"`
	// activity type (Transfer, Install, Rollback)
	Activity string `json:"activity,omitempty"`
	// status tyoe (Cancel, Running Complete,TransferCompleted, Failed,Unavailable)
	Status string `json:"status,omitempty"`
	// massage
	Message string `json:"message,omitempty"`
	// creation time
	CreationTime string `json:"creationTime,omitempty"`
	// transfer start time
	TransferStartTime string `json:"transferStartTime,omitempty"`
	// transfer end time
	TransferEndTime string `json:"transferEndTime,omitempty"`
	// installation start time
	InstallStartTime string `json:"installStartTime,omitempty"`
	// installation end time
	InstallEndTime string `json:"installEndTime,omitempty"`
	// activity name
	ActivityName string `json:"activityName,omitempty"`
	// install user
	InstallUser string `json:"installUser,omitempty"`
	// notify address
	NotifyAddress string `json:"notifyAddress,omitempty"`
	// description
	Description string `json:"description,omitempty"`
}
