/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type UserHeader struct {
	// user name
	Name string `json:"name,omitempty"`
	// full user name
	FullName string `json:"fullName,omitempty"`
	// user description
	Description string `json:"description,omitempty"`
	// user status (output only)
	Status string `json:"status,omitempty"`
	// updated date (output only)
	LastUpdated string `json:"lastUpdated,omitempty"`
	// create date (output only)
	Created string `json:"created,omitempty"`
	// list of groups user belongs to
	MemberOf []string `json:"memberOf,omitempty"`
}
