/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type AgentDetails struct {
	// agent machine
	Nodeid string `json:"nodeid,omitempty"`
	// agent status
	Status string `json:"status,omitempty"`
	// list of hostgroups names containing the agent
	Hostgroups []string `json:"hostgroups,omitempty"`
	// agent version string i.e. - 9.0.20.080
	Version string `json:"version,omitempty"`
	// agent operating system long name i.e - Microsoft Windows Server 2016  (Build 14393)
	OperatingSystem string `json:"operatingSystem,omitempty"`
}
