/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RawCmsXmlRequest struct {
	// The raw XML request string
	RawXmlRequest string `json:"rawXmlRequest,omitempty"`
	EncryptionMetadata *EncryptionMetadata `json:"encryptionMetadata,omitempty"`
}
