/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type Performance struct {
	// the type of the availability metric
	Type_ string `json:"Type,omitempty"`
	// the name of the metric
	Name string `json:"Name,omitempty"`
	// the unit of measurement
	Unit string `json:"Unit,omitempty"`
	// the value of the metric
	Value int32 `json:"Value,omitempty"`
}
