/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go
import (
	"os"
)

type Body7 struct {
	// File with contenet of Role Data.
	RoleFile **os.File `json:"roleFile"`
}
