/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ClientAccessPrivilegeCategory struct {
	// Control-M Self Service access level (None, Full)
	SelfServiceAccess string `json:"SelfServiceAccess,omitempty"`
	// Control-M Workload Change Manager access level (None, Full)
	WorkloadChangeManagerAccess string `json:"WorkloadChangeManagerAccess,omitempty"`
	// Control-M, Utilitiesm EM API, BIM Web, UI access level (None, Full)
	UtilitiesAccess string `json:"UtilitiesAccess,omitempty"`
	// Control-M Application Integrator access level (None, Full)
	ApplicationIntegratorAccess string `json:"ApplicationIntegratorAccess,omitempty"`
	// Control-M Automation API access level (None, Full)
	AutomationAPIAccess string `json:"AutomationAPIAccess,omitempty"`
	// Control-M Workflow Insights access level (None, Full)
	WorkflowInsightsAccess string `json:"WorkflowInsightsAccess,omitempty"`
}
