/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RunAsUserData struct {
	// agent name, can ended by wildcard REQUIRED
	Agent string `json:"agent,omitempty"`
	// user name REQUIRED
	User string `json:"user,omitempty"`
	// Password
	Password string `json:"password,omitempty"`
	Key *RunAsUserKeyData `json:"key,omitempty"`
}
