/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go
import (
	"os"
)

type Body5 struct {
	// File that contains the definitions of the jobs to run. It can be a JSON file, or a zip file that can contain one or more JSON files, as well as account(s) information.
	JobDefinitionsFile **os.File `json:"jobDefinitionsFile"`
	// Deploy Descriptor JSON file.
	DeployDescriptorFile **os.File `json:"deployDescriptorFile,omitempty"`
	// additionalConfiguration to enable skip testing for local connection profile
	AdditionalConfiguration **os.File `json:"additionalConfiguration,omitempty"`
}
