/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ActionsAuthRecord struct {
	// component in which the action sent - Possible Values - EM, CTM_Server, CTM_Agent, CTM_CM
	Destination string `json:"destination,omitempty"`
	// action name unique list of actions' names as appear in the actions_auth em db table, along with the destination makes a unique action auth entry
	Action string `json:"action,omitempty"`
	// Privilege (Can be empty) Possible Values for categories fields  - OPER, DATABASE, CONFIG, CTMSEC, CPMAN, RAMAN, AGMAN, CMMAN, CCP, UNKNOWN
	Category string `json:"category,omitempty"`
	// required minimum authorization level - BROWSE, UPDATE, FULL
	AuthLevel string `json:"authLevel,omitempty"`
	// R - request always pass, authorization is done on the response; C - Connection Profile name will remain empty and will be ignored; E - Not related to authorization
	ActionType string `json:"actionType,omitempty"`
	// currently not in use regarding authorization
	AdditionalInfo string `json:"additionalInfo,omitempty"`
	Category2 string `json:"category2,omitempty"`
	// relation between Category and category2 - 1. Only category, 2. Only Category2, 3. Category AND Category2, 4. Category OR Category2
	Policy string `json:"policy,omitempty"`
	// In case that not all information for authorization exist in the header request, it contain path in the body for the missing field\\fields.
	AuthAttr string `json:"authAttr,omitempty"`
}
