/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ProvisionAdvanceParameters struct {
	// Which component is allowed to initiate the connection [ServerToAgent | AgentToServer | BothAllowed]. Parameters start with capital letter.  HIDDEN.
	ConnectionInitiator string `json:"connectionInitiator,omitempty"`
	// Logical name that is used to label specific Control-M/Agents into a group with a specific authorization level.  HIDDEN.
	Tag string `json:"tag,omitempty"`
	// Control-M/Server name (in case it has an alias or multiple network interfaces).  HIDDEN.
	ServerHostName string `json:"serverHostName,omitempty"`
	// Control-M/Server port to communicate with the agent.  HIDDEN.
	ServerPort int32 `json:"serverPort,omitempty"`
}
