/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type FolderProperties struct {
	// The name of the folder. REQUIRED:addMFTFolder | HIDDEN
	Name string `json:"name,omitempty"`
	// Authorized Internal Users. HIDDEN
	AllowedInternalUserNames []string `json:"allowedInternalUserNames,omitempty"`
	// Authorized External Users And User Groups. HIDDEN
	AllowedUserNames []string `json:"allowedUserNames,omitempty"`
	// Array of allowed group names. HIDDEN
	AllowedGroupNames []string `json:"allowedGroupNames,omitempty"`
	// Delete file after downloaded from incoming folder. HIDDEN
	DeleteFilesAfterProcessing bool `json:"deleteFilesAfterProcessing,omitempty"`
	// Send email notification to external users when a new file arrives. HIDDEN
	NotifyByEmailWhenFileArrived bool `json:"notifyByEmailWhenFileArrived,omitempty"`
	// Retention Time in hours. HIDDEN
	RetentionHours int64 `json:"retentionHours,omitempty"`
	// Size limit for folder (in Gigabyte). HIDDEN
	SizeLimit int64 `json:"sizeLimit,omitempty"`
	// allowed file pattern wildcard. HIDDEN
	AllowedFilePattern string `json:"allowedFilePattern,omitempty"`
	// blocked file pattern wildcard. HIDDEN
	ExcludeFilePattern string `json:"excludeFilePattern,omitempty"`
	// Folder's access type (Limited, Unlimited). HIDDEN
	AccessType string `json:"accessType,omitempty"`
}
