/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go
import (
	"os"
)

type Body struct {
	// A file that contains definitions to be deployed to the server. Can be either a JSON definition file, an XML definition file, or a zip file that contains multiple JSON or XML definition files.
	DefinitionsFile **os.File `json:"definitionsFile"`
	// Deploy Descriptor JSON file.
	DeployDescriptorFile **os.File `json:"deployDescriptorFile,omitempty"`
	// additionalConfiguration to enable skip testing for local connection profile
	AdditionalConfiguration **os.File `json:"additionalConfiguration,omitempty"`
}
