/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type SearchParams struct {
	// The name of sthe Control-M server in which the job was ordered from. HIDDEN.
	Ctm string `json:"ctm,omitempty"`
	// The name of the job. HIDDEN.
	JobName string `json:"jobName,omitempty"`
	// The name of the application the jobs belong to. HIDDEN.
	App string `json:"app,omitempty"`
	// The name of the sub-application the jobs belong to. HIDDEN.
	SubApp string `json:"subApp,omitempty"`
	// The name of the parent folder. HIDDEN.
	Folder string `json:"folder,omitempty"`
	// The job's end status. HIDDEN.
	Status string `json:"status,omitempty"`
	// The job's library name. HIDDEN.
	Lib string `json:"lib,omitempty"`
	// Maximum archived Jobs to display. HIDDEN.
	Limit int32 `json:"limit,omitempty"`
	// Job log must contain the given phrase. HIDDEN.
	LogContains string `json:"logContains,omitempty"`
	// Job output must contain the given phrase. HIDDEN.
	OutputContains string `json:"outputContains,omitempty"`
	// Member's library. HIDDEN.
	MemLib string `json:"memLib,omitempty"`
	// Member name. HIDDEN.
	MemName string `json:"memName,omitempty"`
	// Job's node group. HIDDEN.
	NodeGroup string `json:"nodeGroup,omitempty"`
	// Job's node id (agent). HIDDEN.
	NodeId string `json:"nodeId,omitempty"`
	// Indicating a date by which will look for jobs that their order date started afterwards. Date format - YYYY-MM-DD. HIDDEN.
	FromOrderDate string `json:"fromOrderDate,omitempty"`
	// Indicating a date by which will look for jobs that their order date ended before. Date format - YYYY-MM-DD. HIDDEN.
	ToOrderDate string `json:"toOrderDate,omitempty"`
	// Job's order id. HIDDEN.
	OrderId string `json:"orderId,omitempty"`
	// Runs as (username on agent machine). HIDDEN.
	RunAs string `json:"runAs,omitempty"`
	// Job execution start date. Date format - YYYY-MM-DD. HIDDEN.
	StartDate string `json:"startDate,omitempty"`
	// Job execution end date. Date format - YYYY-MM-DD. HIDDEN.
	EndDate string `json:"endDate,omitempty"`
}
