/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type OrderFolderParameters struct {
	// The Control-M Server to order from. REQUIRED.
	Ctm string `json:"ctm,omitempty"`
	// The folder to order. REQUIRED.
	Folder string `json:"folder,omitempty"`
	// Filter the jobs to order.
	Jobs string `json:"jobs,omitempty"`
	// The z/os library that contains the job (only for MF).
	Library string `json:"library,omitempty"`
	// Is it allowed to order the same jobs more than once to the same SMART folder. HIDDEN.
	CreateDuplicate bool `json:"createDuplicate,omitempty"`
	// Are jobs ordered in a HOLD state. HIDDEN.
	Hold bool `json:"hold,omitempty"`
	// Is scheduling criteria to be ignored. HIDDEN.
	IgnoreCriteria bool `json:"ignoreCriteria,omitempty"`
	// Whether to generate new flow in this order. HIDDEN.
	IndependentFlow bool `json:"independentFlow,omitempty"`
	// The order date that is attached to this order command. HIDDEN.
	OrderDate string `json:"orderDate,omitempty"`
	// Policy for placing the jobs in a SMART folder. HIDDEN.
	OrderIntoFolder string `json:"orderIntoFolder,omitempty"`
	// Whether to wait for the order date when running the jobs. HIDDEN.
	WaitForOrderDate bool `json:"waitForOrderDate,omitempty"`
	// Job Variables for this run. HIDDEN.
	Variables []map[string]string `json:"variables,omitempty"`
}
