/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type UpgradeRequest struct {
	// Control-M name. REQUIRED
	Ctm string `json:"ctm,omitempty"`
	// Agent name. REQUIRED
	Agent string `json:"agent,omitempty"`
	// Product type (Agent, MFT, AppPack). REQUIRED
	Type_ string `json:"type,omitempty"`
	// Target version to be installed or version that should be rollback REQUIRED
	Version string `json:"version,omitempty"`
	// Name of activity
	ActivityName string `json:"activityName,omitempty"`
	// User that will install, upgrade or uninstall HIDDEN
	InstallUser string `json:"installUser,omitempty"`
	// List of email addresses separated by semicolon HIDDEN
	NotifyAddress string `json:"notifyAddress,omitempty"`
	// Description of activity HIDDEN
	Description string `json:"description,omitempty"`
}
