/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type GetManifestParams struct {
	// Holds the category of the entry
	Category string `json:"category,omitempty"`
	// Order of appearance
	Order int32 `json:"order,omitempty"`
	// Three letters that are the product unique identifier
	ProductCode string `json:"productCode,omitempty"`
	// The full official name of the product
	Name string `json:"name,omitempty"`
	// Specifies the path to the installation file
	InstallUri string `json:"installUri,omitempty"`
	// Determines whether or not the product should be visible in the web page
	Visible bool `json:"visible,omitempty"`
	// Base64 representaion of image file
	IconBase64 string `json:"iconBase64,omitempty"`
	// Description of the specific error
	Error_ string `json:"error,omitempty"`
	// Http response status code
	ErrorCode string `json:"errorCode,omitempty"`
	// The full name
	FullName string `json:"fullName,omitempty"`
	// The short name
	ShortName string `json:"shortName,omitempty"`
	// List of words that user can use when searching for a plugin
	Keywords []string `json:"keywords,omitempty"`
	// Includes all the versions numbers of the product that exist in the repository
	Versions []string `json:"versions,omitempty"`
	Group *ManifestGroupObject `json:"group,omitempty"`
}
