/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// Application integrator jobtype
type AiJobtype struct {
	// Jobtype display name
	JobTypeName string `json:"jobTypeName,omitempty"`
	// Jobtype internal appname
	JobTypeId string `json:"jobTypeId,omitempty"`
	// Jobtype status ['ready to deploy', 'draft']
	Status string `json:"status,omitempty"`
	// Jobtype description
	Description string `json:"description,omitempty"`
}
