/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// SFTP server parameters
type FtsSftpSettings struct {
	// Enable/Disable listening for SFTP connection
	ServerEnabled bool `json:"serverEnabled,omitempty"`
	// SFTP server port
	Port int32 `json:"port,omitempty"`
	// Authentication method being used to connect FTP server
	AuthenticationMethod string `json:"authenticationMethod,omitempty"`
	// SFTP keystore file location
	KeystoreFilePath string `json:"keystoreFilePath,omitempty"`
	// Password being used to access the SFTP keystore
	KeystoreFilePassword string `json:"keystoreFilePassword,omitempty"`
	// Ftps server allowed cipher suites (comma-separated). Leave empty to allow all supported cipher suites.
	Ciphers string `json:"ciphers,omitempty"`
	// Known users file location
	KnownUsersFilePath string `json:"knownUsersFilePath,omitempty"`
	// Overridden home directories for specific internal users
	OverriddenUsersHomeDirectories []FtsUserHomeDirectoryData `json:"overriddenUsersHomeDirectories,omitempty"`
}
