/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ServiceAuthAction struct {
	// Is DrillDown allowed in service
	DrillDown bool `json:"DrillDown,omitempty"`
	// Is Run allowed in service
	Run bool `json:"Run,omitempty"`
	// Is Hold allowed in service
	Hold bool `json:"Hold,omitempty"`
	// Is Resume allowed in service
	Resume bool `json:"Resume,omitempty"`
	// Is View Orderable Service allowed in service
	ViewOrderableService bool `json:"ViewOrderableService,omitempty"`
}
