/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type KeyValueType struct {
	// Unique key
	Name string `json:"name"`
	// Any value in string form.
	Value string `json:"value"`
	// The default value if exist.
	DefaultValue string `json:"defaultValue,omitempty"`
	// the type of the request.
	Type_ string `json:"type,omitempty"`
}
