/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type Variables struct {
	// Key value map where key is pool variables in format %%\\\\PoolName\\AUTOVarInPool. HIDDEN.
	Variables []map[string]string `json:"variables,omitempty"`
}
