/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type CtmagentStateChangedType struct {
	// the Agent state change timestamp
	Timestamp string `json:"timestamp,omitempty"`
	// the Agent state change status
	Status string `json:"status,omitempty"`
	// the Agent state change message
	Message string `json:"message,omitempty"`
	// the state change ordinal
	Ordinal int32 `json:"ordinal,omitempty"`
}
