/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type CtmDetails struct {
	// The unique name of the Control-M Server.
	Name string `json:"name,omitempty"`
	// The hostname of the Control-M Server is running on.
	Host string `json:"host,omitempty"`
	// Control-M Server state [up|down].
	State string `json:"state,omitempty"`
	// Control-M Server message describing the communication status.
	Message string `json:"message,omitempty"`
	// Control-M Server version.
	Version string `json:"version,omitempty"`
}
