/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type Saml2IdentityProvider struct {
	MetadataUrl string `json:"metadataUrl"`
	Enabled bool `json:"enabled"`
	ServiceProviderInformation *ServiceProviderInformation `json:"serviceProviderInformation,omitempty"`
}
