/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type PoolVariablesNameValue struct {
	PoolName string `json:"pool_name,omitempty"`
	VariableNameValue []VariableNameValue `json:"variable_name_value,omitempty"`
}
