/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type AllowedJobActions struct {
	// True if Properties action is allowed
	ViewProperties bool `json:"ViewProperties,omitempty"`
	// True if Documentation action is allowed
	Documentation bool `json:"Documentation,omitempty"`
	// True if Log action is allowed
	Log bool `json:"Log,omitempty"`
	// True if Statistics action is allowed
	Statistics bool `json:"Statistics,omitempty"`
	// True if ViewOutputList action is allowed
	ViewOutputList bool `json:"ViewOutputList,omitempty"`
	// True if ViewJcl action is allowed
	ViewJcl bool `json:"ViewJcl,omitempty"`
	// True if Why action is allowed
	Why bool `json:"Why,omitempty"`
	// True if Hold action is allowed
	Hold bool `json:"Hold,omitempty"`
	// True if Free action is allowed
	Free bool `json:"Free,omitempty"`
	// True if Confirm action is allowed
	Confirm bool `json:"Confirm,omitempty"`
	// True if Rerun action is allowed
	Rerun bool `json:"Rerun,omitempty"`
	// True if React action is allowed
	React bool `json:"React,omitempty"`
	// True if Restart action is allowed
	Restart bool `json:"Restart,omitempty"`
	// True if Kill action is allowed
	Kill bool `json:"Kill,omitempty"`
	// True if Bypass action is allowed
	Bypass bool `json:"Bypass,omitempty"`
	// True if Delete action is allowed
	Delete bool `json:"Delete,omitempty"`
	// True if Undelete action is allowed
	Undelete bool `json:"Undelete,omitempty"`
	// True if SetToOk action is allowed
	SetToOk bool `json:"SetToOk,omitempty"`
	// True if EditProperties action is allowed
	EditProperties bool `json:"EditProperties,omitempty"`
	// True if EditJcl action is allowed
	EditJcl bool `json:"EditJcl,omitempty"`
}
