/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type As2KeyData struct {
	// as2 id HIDDEN
	As2Id string `json:"as2Id,omitempty"`
	// partners certificate alias HIDDEN
	Certificate string `json:"certificate,omitempty"`
	// AS2 destination folder HIDDEN
	DestinationFolder string `json:"destinationFolder,omitempty"`
}
