/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type MftConfigurationData struct {
	// Connection timeout (seconds) HIDDEN
	ConnectionTimeoutInSeconds int32 `json:"connectionTimeoutInSeconds,omitempty"`
	// Number of connection retries HIDDEN
	ConnectionRetries int32 `json:"connectionRetries,omitempty"`
	// Time between connection retries (seconds) HIDDEN
	ConnectionTimeBetweenRetriesInSeconds int32 `json:"connectionTimeBetweenRetriesInSeconds,omitempty"`
	// MFT debug level (0-5) HIDDEN
	DebugLevel int32 `json:"debugLevel,omitempty"`
	// PGP temporary directory HIDDEN
	PgpTempDir string `json:"pgpTempDir,omitempty"`
	// Enable SSL debug trace HIDDEN
	SslDebugTrace bool `json:"sslDebugTrace,omitempty"`
	// Use PAM password authentication HIDDEN
	PamAuthentication bool `json:"pamAuthentication,omitempty"`
	// Use web proxy HIDDEN
	ProxyIsInUse bool `json:"proxyIsInUse,omitempty"`
	// Proxy host HIDDEN
	ProxyHost string `json:"proxyHost,omitempty"`
	// Proxy port HIDDEN
	ProxyPort int32 `json:"proxyPort,omitempty"`
	// Proxy user HIDDEN
	ProxyUser string `json:"proxyUser,omitempty"`
	// Proxy password HIDDEN
	ProxyPassword string `json:"proxyPassword,omitempty"`
	// File watch search interval (seconds) HIDDEN
	FileWatcherSearchInterval int32 `json:"fileWatcherSearchInterval,omitempty"`
	// Number of iterations while file is static HIDDEN
	FileWatcherStaticIterations int32 `json:"fileWatcherStaticIterations,omitempty"`
	// Check that file is not in use HIDDEN
	FileWatcherCheckFileIsInUse bool `json:"fileWatcherCheckFileIsInUse,omitempty"`
	// File action retry interval (seconds) HIDDEN
	FileActionsRetriesIntervalInSeconds int32 `json:"fileActionsRetriesIntervalInSeconds,omitempty"`
	// Number of file action retries HIDDEN
	FileActionsRetriesNum int32 `json:"fileActionsRetriesNum,omitempty"`
}
