/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type WorkloadPolicy struct {
	// unique workload policy name
	Name string `json:"name,omitempty"`
	// workload policy state
	State string `json:"state,omitempty"`
	// workload policy order number
	OrderNo string `json:"orderNo,omitempty"`
	// workload policy update date
	LastUpdate string `json:"lastUpdate,omitempty"`
	// user which updated workload policy
	UpdatedBy string `json:"updatedBy,omitempty"`
	// workload policy description
	Description string `json:"description,omitempty"`
}
