/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ZooKeeper struct {
	// zookeeper Id
	ZookeeperId int32 `json:"zookeeperId,omitempty"`
	// zookeeper Server Host
	ZookeeperServerHost string `json:"zookeeperServerHost,omitempty"`
	// zookeeper Admin Server Port
	ZookeeperAdminServerPort int32 `json:"zookeeperAdminServerPort,omitempty"`
	// zookeeper Client Port
	ZookeeperClientPort int32 `json:"zookeeperClientPort,omitempty"`
	// zookeeper Leader Port
	ZookeeperLeaderPort int32 `json:"zookeeperLeaderPort,omitempty"`
	// zookeeper Leader Election Port
	ZookeeperLeaderElectionPort int32 `json:"zookeeperLeaderElectionPort,omitempty"`
}
