/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type PgpTemplateData struct {
	// Template name HIDDEN
	Name string `json:"name,omitempty"`
	// Executable Full Path HIDDEN
	ExecutableFullPath string `json:"executableFullPath,omitempty"`
	// Exit code (default 0) HIDDEN
	ExitCode int32 `json:"exitCode,omitempty"`
	// passphrase HIDDEN
	Passphrase string `json:"passphrase,omitempty"`
	// Recipient HIDDEN
	Recipient string `json:"recipient,omitempty"`
	// Encryption Attributes HIDDEN
	EncryptionAttributes string `json:"encryptionAttributes,omitempty"`
	// Decryption Attributes HIDDEN
	DecryptionAttributes string `json:"decryptionAttributes,omitempty"`
}
