/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ConnectionProfileStatus struct {
	// connection profile name
	Name string `json:"name,omitempty"`
	// connection profile type
	Type_ string `json:"type,omitempty"`
	// connection profile description
	Description string `json:"description,omitempty"`
	// UTC date of the modification
	TimeModified string `json:"timeModified,omitempty"`
	// UTC date of the creation
	TimeCreated string `json:"timeCreated,omitempty"`
	// creator's name
	CreatorName string `json:"creatorName,omitempty"`
	// modifier's name
	ModifierName string `json:"modifierName,omitempty"`
	// Status calculated by the server according to the list of statuses with each server
	SyncStatus string `json:"syncStatus,omitempty"`
}
