/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type PluginData struct {
	// The application type
	ApplicationType string `json:"applicationType,omitempty"`
	// The application version
	ApplicationVersion string `json:"applicationVersion,omitempty"`
	// The plugin version
	PluginVersion string `json:"pluginVersion,omitempty"`
	// The version
	Version string `json:"version,omitempty"`
	// The current state
	CurrentState string `json:"currentState,omitempty"`
	// The status
	Status string `json:"status,omitempty"`
	// The status message
	StatusMessage string `json:"statusMessage,omitempty"`
	// The last update
	LastUpdate string `json:"lastUpdate,omitempty"`
	// The B2B activated indication
	B2bActivated string `json:"b2bActivated,omitempty"`
}
