/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type PossibleValueProperties struct {
	Label string `json:"label,omitempty"`
	LabelID string `json:"labelID,omitempty"`
	Value string `json:"value,omitempty"`
}
