/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type SshKeyProperties struct {
	// External user data REQUIRED
	KeyName string `json:"keyName,omitempty"`
	// SSH Key passphrase REQUIRED
	KeyPassphrase string `json:"keyPassphrase,omitempty"`
	// SSH Key size (default 2048)
	KeySize int32 `json:"keySize,omitempty"`
}
