/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type Privileges struct {
	ClientAccess *ClientAccessPrivilegeCategory `json:"ClientAccess,omitempty"`
	ConfigurationManager *ConfigurationManagerPrivilegeCategory `json:"ConfigurationManager,omitempty"`
	Monitoring *MonitoringPrivilegeCategory `json:"Monitoring,omitempty"`
	Planning *PlanningPrivilegeCategory `json:"Planning,omitempty"`
	Tools *ToolsPrivilegeCategory `json:"Tools,omitempty"`
	ViewpointManager *ViewpointManagerPrivilegeCategory `json:"ViewpointManager,omitempty"`
}
