/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// Home directory for specific user
type FtsUserHomeDirectoryData struct {
	// User name
	UserName string `json:"userName,omitempty"`
	// Home directory
	HomeDirectory string `json:"homeDirectory,omitempty"`
}
