/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type AllowedJobs struct {
	// list of including term Groups, combined by OR
	Included [][][]string `json:"Included,omitempty"`
	// list of excluding term Groups, combined by OR
	Excluded [][][]string `json:"Excluded,omitempty"`
}
