/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RuleProjection struct {
	Description string `json:"description,omitempty"`
	LastUpdatedTimestamp int64 `json:"lastUpdatedTimestamp,omitempty"`
	Name string `json:"name,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	SearchTags []SearchTagTuple `json:"searchTags,omitempty"`
	Status string `json:"status,omitempty"`
}
