/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type TokenDataResponse struct {
	// required field. HIDDEN.
	TokenName string `json:"tokenName"`
	// required field. HIDDEN.
	TokenType string `json:"tokenType"`
	// required field. HIDDEN.
	TokenValue string `json:"tokenValue"`
	// is not provided in API Token for Agent. HIDDEN.
	User string `json:"user,omitempty"`
	// is not provided in API Token for Agent. HIDDEN.
	Roles []string `json:"roles,omitempty"`
	// optional field. HIDDEN.
	ExpirationDate string `json:"expirationDate,omitempty"`
	// transient field. HIDDEN.
	CreatedDate string `json:"createdDate,omitempty"`
	// transient field. HIDDEN.
	LastUpdatedDate string `json:"lastUpdatedDate,omitempty"`
}
