/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type AddAgentParams struct {
	// The hostname or alias of the agent machine.
	Host string `json:"host"`
	// The agent's listening port.
	Port int32 `json:"port"`
	// The agent's tag.
	Tag string `json:"tag,omitempty"`
	// The agent's ssl State. HIDDEN.
	SslState string `json:"sslState,omitempty"`
	// Is the connection persistent or create each time it is needed. HIDDEN.
	PersistentConnection bool `json:"persistentConnection,omitempty"`
	// maximum time in seconds to wait (default 60). HIDDEN
	Timeout int32 `json:"timeout,omitempty"`
	// Suppress ping action to added agent (default false). HIDDEN.
	SuppressPing bool `json:"suppressPing,omitempty"`
}
