/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type LogJobParameters struct {
	FromRerunCount string `json:"from_rerun_count,omitempty"`
	OrderId string `json:"order_id,omitempty"`
	ToRerunCount string `json:"to_rerun_count,omitempty"`
}
