/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type Statistics struct {
	// Statistics calendar period
	CurrentPeriod string `json:"currentPeriod,omitempty"`
	// Statistics calendar Control-M
	CalendarControlm string `json:"calendarControlm,omitempty"`
	// Statistics calendar name
	CalendarName string `json:"calendarName,omitempty"`
	Periods []StatisticsPeriod `json:"periods,omitempty"`
}
