/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type CtmagentCtmTestType struct {
	// the test title
	Title string `json:"title,omitempty"`
	// the test result
	Result string `json:"result,omitempty"`
	// the test message
	Message string `json:"message,omitempty"`
	// the action user initiated
	UserAction string `json:"userAction,omitempty"`
	// the test's command
	Command string `json:"command,omitempty"`
	// the command's output
	CommandOutput string `json:"commandOutput,omitempty"`
	// the test advanced option
	Advanced int32 `json:"advanced,omitempty"`
	// the test oridnal
	Ordinal int32 `json:"ordinal,omitempty"`
}
