/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go
import (
	"os"
)

type Body1 struct {
	// A file that contains definitions of the connection profile to be tested
	DefinitionsFile **os.File `json:"definitionsFile"`
}
