/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RuleStatistics struct {
	RuleName string `json:"ruleName,omitempty"`
	Retention int32 `json:"retention,omitempty"`
	RetentionType string `json:"retentionType,omitempty"`
	OldestItem string `json:"oldestItem,omitempty"`
	NewestItem string `json:"newestItem,omitempty"`
	TotalJobs int32 `json:"totalJobs,omitempty"`
	DataSize string `json:"dataSize,omitempty"`
}
