/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go
import (
	"os"
)

type Body6 struct {
	// File that contains the definitions of the job to modify. It should be a JSON file.
	JobDefinitionsFile **os.File `json:"jobDefinitionsFile"`
}
