/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type Event struct {
	// Event name
	Name string `json:"name,omitempty"`
	// Control-M Server hosting the event
	Ctm string `json:"ctm,omitempty"`
	// The event date, either date in format dd/mm/yy or a string \"orderdate\"
	Date string `json:"date,omitempty"`
}
