/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RunasDefinitionAuth struct {
	// control-M server name
	ControlmServer string `json:"ControlmServer,omitempty"`
	// access level (full, update, browse)
	Privilege string `json:"Privilege,omitempty"`
}
