/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type CtmagentBasicInfoType struct {
	// server to agent port number
	ServerToAgentPortNumber int32 `json:"serverToAgentPortNumber,omitempty"`
	// agent to server port number
	AgentToServerPortNumber int32 `json:"agentToServerPortNumber,omitempty"`
	// is Server-Agent connection transient or perssistent
	PersistentConnection string `json:"persistentConnection,omitempty"`
	// is connection TCP or SSL
	TcpsslServerMode string `json:"tcpsslServerMode,omitempty"`
	// communication protocol version of the Server-Agent
	ProtocolVersion string `json:"protocolVersion,omitempty"`
	// the Agent's status message
	AgentStatus string `json:"agentStatus,omitempty"`
	IpAddressesList []string `json:"ipAddressesList,omitempty"`
}
