/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// Response of deploy and pre-deploy AI jobtype
type AiDeployResponse struct {
	// response message
	Message string `json:"message,omitempty"`
}
