/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ViewpointManagerPrivilegeCategory struct {
	// Collections access level (None, Browse, Update, Full)
	Collections string `json:"Collections,omitempty"`
	// Hierarchies access level (None, Browse, Update, Full)
	Hierarchies string `json:"Hierarchies,omitempty"`
	// Filters access level (None, Browse, Update, Full)
	Filters string `json:"Filters,omitempty"`
	// Viewpoints access level (None, Browse, Update, Full)
	Viewpoints string `json:"Viewpoints,omitempty"`
}
