/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type PlanningPrivilegeCategory struct {
	// Periodical Statistics access level (None, Browse, Update, Full)
	PeriodicalStatistics string `json:"PeriodicalStatistics,omitempty"`
	// Forecast/BIM Configuration access level (None, Browse, Update, Full)
	ForecastOrBatchImpactManagerConfig string `json:"ForecastOrBatchImpactManagerConfig,omitempty"`
	// Promotion Rules access level (None, Browse, Update, Full)
	PromotionRules string `json:"PromotionRules,omitempty"`
	// Promote Action access level (None, Browse, Update, Full)
	PromoteAction string `json:"PromoteAction,omitempty"`
}
