/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ToolsPrivilegeCategory struct {
	// CLI access level (None, Browse, Update, Full)
	Cli string `json:"Cli,omitempty"`
	// BIM Reports access level (None, Browse, Update, Full)
	BatchImpactManagerReport string `json:"BatchImpactManagerReport,omitempty"`
	// Forecast Reports access level (None, Browse, Update, Full)
	ForecastReport string `json:"ForecastReport,omitempty"`
}
