/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type UserAdditionalProperties struct {
	// List of role names
	MemberOfGroups []string `json:"memberOfGroups,omitempty"`
	Authentication *AuthenticationData `json:"authentication,omitempty"`
	IsExternalUser bool `json:"isExternalUser,omitempty"`
}
