/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type StatisticsRunInfo struct {
	AverageInfo *StatisticsAverageInfo `json:"averageInfo,omitempty"`
	Runs []StatisticsSingleRun `json:"runs,omitempty"`
}
