/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type SlaServiceStatusByJobs struct {
	// Executed
	Executed string `json:"executed,omitempty"`
	// Wait Condition
	WaitCondition string `json:"waitCondition,omitempty"`
	// Wait Resource
	WaitResource string `json:"waitResource,omitempty"`
	// Wait User
	WaitUser string `json:"waitUser,omitempty"`
	// Wait Host
	WaitHost string `json:"waitHost,omitempty"`
	// Wait Workload
	WaitWorkload string `json:"waitWorkload,omitempty"`
	// Completed
	Completed string `json:"completed,omitempty"`
	// Error
	Error_ string `json:"error,omitempty"`
	// Unkwown
	Unknown string `json:"unknown,omitempty"`
}
