/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type UserData struct {
	// user name
	Name string `json:"Name,omitempty"`
	// user description
	Description string `json:"Description,omitempty"`
	// full user name
	FullName string `json:"FullName,omitempty"`
	Authentication *AuthenticationData `json:"Authentication,omitempty"`
	Roles []string `json:"Roles,omitempty"`
	Authorization *RoleData `json:"Authorization,omitempty"`
}
