/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type FolderAuth struct {
	// access level (Full, Update, Browse)
	Privilege string `json:"Privilege,omitempty"`
	// control-M server name
	ControlmServer string `json:"ControlmServer,omitempty"`
	// job application
	Library string `json:"Library,omitempty"`
	// job sub application
	Folder string `json:"Folder,omitempty"`
	// Allow ordering
	Order bool `json:"Order,omitempty"`
	// Allow ordering
	Run bool `json:"Run,omitempty"`
	Jobs *JobLevelAuth `json:"Jobs,omitempty"`
}
