/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// File Transfer Server authentication parameters
type FtsAuthenticationDetails struct {
	LdapAuthenticationDetails *FtsLdapAuthenticationDetails `json:"ldapAuthenticationDetails,omitempty"`
	PamAuthenticationDetails *FtsPamAuthenticationDetails `json:"pamAuthenticationDetails,omitempty"`
}
