/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ProductDescription struct {
	// The product name.
	ProductName string `json:"productName,omitempty"`
	// The product description.
	ProductDescription string `json:"productDescription,omitempty"`
	// is Section open.
	IsSectionOpen bool `json:"isSectionOpen,omitempty"`
	// is static text section.
	StaticText bool `json:"staticText,omitempty"`
	// is token component added.
	TokenComponent bool `json:"tokenComponent,omitempty"`
}
