/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type Sample struct {
	Id int64 `json:"id"`
	Title string `json:"title"`
	Description string `json:"description,omitempty"`
}
