/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type EncryptionMetadata struct {
	// The type of encryption algorithm to be used to de/encrypt the fields (AES256 or Blowfish)
	EncryptionType string `json:"encryptionType,omitempty"`
	// The list of XML tag names identifying the fields to be de/encrypted in the request XML
	FieldsToEncrypt []string `json:"fieldsToEncrypt,omitempty"`
}
