/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type JobRunStatus struct {
	// Order ID of the job.
	JobId string `json:"jobId"`
	// Order ID of the folder containing this job.
	FolderId string `json:"folderId,omitempty"`
	// The run number (in case of cyclic jobs or reruns)
	NumberOfRuns int64 `json:"numberOfRuns,omitempty"`
	// The name of the run job.
	Name string `json:"name,omitempty"`
	// The name of the run job.
	Folder string `json:"folder,omitempty"`
	// The type of the run job.
	Type_ string `json:"type,omitempty"`
	// The status of the run job.
	Status string `json:"status,omitempty"`
	// Is job held.
	Held bool `json:"held,omitempty"`
	// Is job held.
	Deleted bool `json:"deleted,omitempty"`
	// Is it a cyclic job.
	Cyclic bool `json:"cyclic,omitempty"`
	// The start time of the job run.
	StartTime string `json:"startTime,omitempty"`
	// The end time of the job run.
	EndTime string `json:"endTime,omitempty"`
	// The estimated start time of the jobs.
	EstimatedStartTime []string `json:"estimatedStartTime,omitempty"`
	// The estimated end time of the jobs.
	EstimatedEndTime []string `json:"estimatedEndTime,omitempty"`
	// The order date.
	OrderDate string `json:"orderDate,omitempty"`
	// The controlm server.
	Ctm string `json:"ctm,omitempty"`
	// The job description.
	Description string `json:"description,omitempty"`
	// host machine where the job runs.
	Host string `json:"host,omitempty"`
	// job application.
	Application string `json:"application,omitempty"`
	// job subApplication.
	SubApplication string `json:"subApplication,omitempty"`
	// The JSON string that describes the job.
	JobJSON string `json:"jobJSON,omitempty"`
	// A URI that can be used to get the output of the run job
	OutputURI string `json:"outputURI,omitempty"`
	// A URI that can be used to get the log of the run job
	LogURI string `json:"logURI,omitempty"`
}
