/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// App list object for AI deploy api
type AppList struct {
	AppNames []App `json:"appNames,omitempty"`
	DeployedNames []AppDeployed `json:"deployedNames,omitempty"`
}
