/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// Object containing Folders for workspace
type WorkspaceFolders struct {
	Folders []WorkspaceFolder `json:"folders,omitempty"`
}
