/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// Deployed app (job type) object for AI deploy api
type AppDeployed struct {
	// job type display name
	Displayname string `json:"displayname,omitempty"`
	// job type name
	Name string `json:"name,omitempty"`
	// version
	Version string `json:"version,omitempty"`
	// default type
	DefaultType string `json:"defaultType,omitempty"`
	// last deployment date
	LastDeployed string `json:"lastDeployed,omitempty"`
	// creation date
	CreatedOn string `json:"createdOn,omitempty"`
	// creation author
	CreatedBy string `json:"createdBy,omitempty"`
}
