/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ArchiveRule struct {
	// The Control-M Workload Archiving rule name. REQUIRED. HIDDEN.
	Name string `json:"name,omitempty"`
	// The description of Control-M Workload Archiving rule. HIDDEN.
	Description string `json:"description,omitempty"`
	// The maximum job's output size to collect. HIDDEN.
	MaxOutputSize string `json:"maxOutputSize,omitempty"`
	// The maximum job's output size type to collect - KB or MB. The default is MB. HIDDEN.
	MaxOutputSizeType string `json:"maxOutputSizeType,omitempty"`
	// Trim in case the output exceed the maximum job's output - Omit , Beginning, End. The default is to Omit. HIDDEN.
	TrimType string `json:"trimType,omitempty"`
	// The retention period to keep archive job by rule. The default is 1. HIDDEN.
	Retention string `json:"retention,omitempty"`
	// The retention period type to keep archive job by rule- Years, Months and Days are available. The default is Years. HIDDEN.
	RetentionType string `json:"retentionType,omitempty"`
	// Is Control-M Workload Archiving rule is active. HIDDEN.
	IsActive string `json:"isActive,omitempty"`
	// The rule archived data - logs, output or both. The default is both. HIDDEN.
	ArchivedType string `json:"archivedType,omitempty"`
	// Rule parameters - ctm, type, jobName, jobType, application, subApplication, jobStatus, folder and library. HIDDEN.
	RuleParameters []RuleCriteria `json:"ruleParameters,omitempty"`
}
