/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RunReport struct {
	Name string `json:"name"`
	Format string `json:"format,omitempty"`
	Filters *[]ReportFilter `json:"filters,omitempty"`
	DateTimeSettings *ReportDateTimeSettings `json:"dateTimeSettings,omitempty"`
}
