/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// Host group data
type HostGroupData struct {
	// Host Group name
	Hostgroup string `json:"hostgroup,omitempty"`
	// Host Group tag
	Tag string `json:"tag,omitempty"`
	// Agents list
	Agentslist []AgentInGroupParams `json:"agentslist,omitempty"`
}
