/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type AddServerParams struct {
	// The Control-M Server host name.
	Host string `json:"host"`
	// The Control-M Server name.
	Ctm string `json:"ctm"`
	// The id of the Control-M Server, 3 digits id
	Id string `json:"id"`
	// The Control-M Server port number.
	Port int32 `json:"port,omitempty"`
}
