/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RoleData struct {
	// role name
	Name string `json:"Name,omitempty"`
	// role description
	Description string `json:"Description,omitempty"`
	// organization groups
	OrganizationGroups []string `json:"OrganizationGroups,omitempty"`
	AllowedJobs *AllowedJobs `json:"AllowedJobs,omitempty"`
	AllowedJobActions *AllowedJobActions `json:"AllowedJobActions,omitempty"`
	Privileges *Privileges `json:"Privileges,omitempty"`
	Folders []FolderAuth `json:"Folders,omitempty"`
	Calendars []PrivilegeNameControlm `json:"Calendars,omitempty"`
	RunasUsers []RunasUserAuth `json:"RunasUsers,omitempty"`
	WorkloadPolicies []PrivilegeName `json:"WorkloadPolicies,omitempty"`
	SiteStandard []PrivilegeName `json:"SiteStandard,omitempty"`
	SiteCustomization []PrivilegeName `json:"SiteCustomization,omitempty"`
	Services []ServiceAuth `json:"Services,omitempty"`
	Events []PrivilegeNameControlm `json:"Events,omitempty"`
	Mutexes []PrivilegeNameControlm `json:"Mutexes,omitempty"`
	Locks []PrivilegeNameControlm `json:"Locks,omitempty"`
	Semaphores []PrivilegeNameControlm `json:"Semaphores,omitempty"`
	Pools []PrivilegeNameControlm `json:"Pools,omitempty"`
	Variables []PrivilegeNameControlm `json:"Variables,omitempty"`
	GlobalEvents []PrivilegeName `json:"GlobalEvents,omitempty"`
	AgentManagement []AgentMngAuth `json:"AgentManagement,omitempty"`
	PluginManagement []PluginMngAuth `json:"PluginManagement,omitempty"`
	ConnectionProfileManagement []CpMngAuth `json:"ConnectionProfileManagement,omitempty"`
	RunasDefinitionManagement []RunasDefinitionAuth `json:"RunasDefinitionManagement,omitempty"`
}
