/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ControlMAuthenticationData struct {
	// password or secret
	Password string `json:"Password,omitempty"`
	// number of days until the password expires
	PasswordExpirationDays int32 `json:"PasswordExpirationDays,omitempty"`
	// should password be changed in next login
	ChangePasswordAtNextLogin bool `json:"ChangePasswordAtNextLogin,omitempty"`
	// lock account
	LockAccount bool `json:"LockAccount,omitempty"`
}
