/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type KeyValue struct {
	// Unique key
	Name string `json:"name"`
	// Any value in string form.
	Value string `json:"value"`
	// The default value if exist.
	DefaultValue string `json:"defaultValue,omitempty"`
	// The validation type number.
	Validation string `json:"validation,omitempty"`
	// The category of the parameter.
	Category string `json:"category,omitempty"`
	// The description of the parameter.
	Description string `json:"description,omitempty"`
	// The error message of the parameter.
	ErrMsg string `json:"errMsg,omitempty"`
	// The verification type of the parameter.
	Verification string `json:"verification,omitempty"`
	// The table the parameter belongs to.
	Table string `json:"table,omitempty"`
	// The parameter type.
	Type_ string `json:"type,omitempty"`
	// The validation limits of the parameter.
	Limits string `json:"limits,omitempty"`
}
