/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type RuleCriteria struct {
	// Rule parameters fields can be one of the options - ctm, type, jobName, jobType, application, subApplication, jobStatus, folder and library. HIDDEN.
	Field string `json:"field,omitempty"`
	Criteria string `json:"criteria,omitempty"`
	Exceptions []string `json:"exceptions,omitempty"`
}
