/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type PrivilegeNameControlm struct {
	// access level (Full, Update, Browse)
	Privilege string `json:"Privilege,omitempty"`
	// control-M server name
	ControlmServer string `json:"ControlmServer,omitempty"`
	// property name
	Name string `json:"Name,omitempty"`
}
