/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ComponentMftKeyType struct {
	// type
	Type_ string `json:"type,omitempty"`
	// name
	Name string `json:"name,omitempty"`
	// host
	Host string `json:"host,omitempty"`
	// node id
	NodeId string `json:"nodeId,omitempty"`
	// application type
	ApplType string `json:"applType,omitempty"`
	// application version
	ApplVer string `json:"applVer,omitempty"`
	// cm version
	CmVer string `json:"cmVer,omitempty"`
}
