/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type PingAgentParams struct {
	// Discover parameter when true the agent will be added to the Control-M. HIDDEN
	Discover bool `json:"discover"`
	// maximum time in seconds to wait (default 60). HIDDEN
	Timeout int32 `json:"timeout"`
}
