/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type AddRemoteHostParams struct {
	// The remote host (name) which will execute the commands. REQUIRED.
	Remotehost string `json:"remotehost,omitempty"`
	// The remote host SSH port.
	Port int32 `json:"port,omitempty"`
	// The SSH encrypt algorithm to be used. HIDDEN.
	EncryptAlgorithm string `json:"encryptAlgorithm,omitempty"`
	// Is compression used. HIDDEN.
	Compression bool `json:"compression,omitempty"`
	// authorize SSL remote host while creating the remote host. HIDDEN.
	Authorize bool `json:"authorize,omitempty"`
	// Agents to execute the commands on. HIDDEN.
	Agents []string `json:"agents,omitempty"`
}
