/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go
import (
	"os"
)

type Body11 struct {
	// The CRT file path.
	CrtFile **os.File `json:"crtFile"`
	// The CA Chain file path.
	CaChainFile **os.File `json:"caChainFile"`
}
