/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// List of application integrator jobtypes
type AiJobtypeList struct {
	Jobtypes []AiJobtype `json:"jobtypes,omitempty"`
}
