/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type AgentData struct {
	// The Agent name
	Name string `json:"name,omitempty"`
	// The Agent host
	Host string `json:"host,omitempty"`
	// The Agent nodeID
	NodeID string `json:"nodeID,omitempty"`
	// The Control-M name
	Ctm string `json:"ctm,omitempty"`
	// The Control-M Host
	CtmHost string `json:"ctmHost,omitempty"`
	// The Agent current state
	CurrentState string `json:"currentState,omitempty"`
	// The Agent status
	Status string `json:"status,omitempty"`
	// The Agent status message
	StatusMessage string `json:"statusMessage,omitempty"`
	// The Agent operating System
	OperatingSystem string `json:"operatingSystem,omitempty"`
	// The Agent platform
	Platform string `json:"platform,omitempty"`
	// The Agent version
	Version string `json:"version,omitempty"`
	// The Agent last update
	LastUpdate string `json:"lastUpdate,omitempty"`
	// The Agent communication version
	CommunicationVersion string `json:"communicationVersion,omitempty"`
	// The Agent tag
	Tag string `json:"tag,omitempty"`
	// The Agent ssl state
	SslState string `json:"sslState,omitempty"`
	// The Agent host groups
	HostGroups string `json:"hostGroups,omitempty"`
	Plugins []PluginData `json:"plugins,omitempty"`
}
