/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type CtmvarErrorInfo struct {
	CtmvarDelErrorCode string `json:"ctmvar_del_error_code,omitempty"`
	CtmvarGetErrorCode string `json:"ctmvar_get_error_code,omitempty"`
	CtmvarSetErrorCode string `json:"ctmvar_set_error_code,omitempty"`
	VariableName string `json:"variable_name,omitempty"`
}
