/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type FieldMetadataProperties struct {
	ControlType string `json:"controlType,omitempty"`
	DataType string `json:"dataType,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	DisplayNameID string `json:"displayNameID,omitempty"`
	FalseValue string `json:"falseValue,omitempty"`
	HashedPassword bool `json:"hashedPassword,omitempty"`
	HideIf *ConditionProperties `json:"hideIf,omitempty"`
	Key *SettingKeyProperties `json:"key,omitempty"`
	Name string `json:"name,omitempty"`
	NeedRestart bool `json:"needRestart,omitempty"`
	NeedRestartMessage string `json:"needRestartMessage,omitempty"`
	NeedRestartMessageID string `json:"needRestartMessageID,omitempty"`
	Placeholder string `json:"placeholder,omitempty"`
	PlaceholderID string `json:"placeholderID,omitempty"`
	PossibleValues []PossibleValueProperties `json:"possibleValues,omitempty"`
	Profiles []string `json:"profiles,omitempty"`
	SettingChangedEventTypes []string `json:"settingChangedEventTypes,omitempty"`
	ShowIf *ConditionProperties `json:"showIf,omitempty"`
	Tooltip string `json:"tooltip,omitempty"`
	TooltipID string `json:"tooltipID,omitempty"`
	TrueValue string `json:"trueValue,omitempty"`
	UnitsLabel string `json:"unitsLabel,omitempty"`
	UnitsLabelID string `json:"unitsLabelID,omitempty"`
	Validations *ValidationProperties `json:"validations,omitempty"`
}
