/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type CommunicationAnalysisResponseType struct {
	BasicInfo *CtmagentBasicInfoType `json:"basicInfo,omitempty"`
	// The list of 4 tests executed and their output
	CtmagentCtmTestsType []CtmagentCtmTestType `json:"ctmagentCtmTestsType,omitempty"`
	// The list of 10 latest Agent's state changed to Unavailable and timestamp
	CtmagentStatesChangedType []CtmagentStateChangedType `json:"ctmagentStatesChangedType,omitempty"`
}
