/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ExternalUserData struct {
	// external user name REQUIRED:addExternalUser | HIDDEN
	Name string `json:"name,omitempty"`
	// user email REQUIRED:addExternalUser | HIDDEN
	Email string `json:"email,omitempty"`
	// user's company REQUIRED:addExternalUser | HIDDEN
	Company string `json:"company,omitempty"`
	// user password HIDDEN:updateExternalUser
	Password string `json:"password,omitempty"`
	// user description HIDDEN
	Description string `json:"description,omitempty"`
	// external user phone number HIDDEN
	PhoneNumber string `json:"phoneNumber,omitempty"`
	// SSH key string HIDDEN
	SshKey string `json:"sshKey,omitempty"`
	As2Key *As2KeyData `json:"as2Key,omitempty"`
	// indicates whether the user account is locked HIDDEN
	IsLocked bool `json:"isLocked,omitempty"`
	// provides the reason for locking the user account HIDDEN
	LockReason string `json:"lockReason,omitempty"`
	// indicates whether a password change is required at next login HIDDEN
	ChangePasswordAtNextLogin bool `json:"changePasswordAtNextLogin,omitempty"`
	// indicates whether the user's password is set to never expire HIDDEN
	PasswordNeverExpires bool `json:"passwordNeverExpires,omitempty"`
}
