/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type AgentInHostgroup struct {
	// The hostname of the agent.
	Host string `json:"host"`
	// Host Group tag. HIDDEN.
	Tag string `json:"tag,omitempty"`
	HostgroupAgentParticipation *HostgroupAgentParticipation `json:"hostgroupAgentParticipation,omitempty"`
}
