/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type SectionMetadataProperties struct {
	DisplayName string `json:"displayName,omitempty"`
	DisplayName1 string `json:"displayName1,omitempty"`
	DisplayNameID string `json:"displayNameID,omitempty"`
	Fields []FieldMetadataProperties `json:"fields,omitempty"`
	Name string `json:"name,omitempty"`
}
