/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type TokenDataRequest struct {
	// required field. HIDDEN.
	TokenName string `json:"tokenName"`
	// required field when creates token for User. HIDDEN.
	Roles []string `json:"roles,omitempty"`
	// optional field. HIDDEN.
	ExpirationDate string `json:"expirationDate,omitempty"`
	// optional field. HIDDEN.
	TokenType string `json:"tokenType,omitempty"`
}
