/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type StatisticsSingleRun struct {
	// job run start time
	StartTime string `json:"startTime,omitempty"`
	// job run end time
	EndTime string `json:"endTime,omitempty"`
	// job run CPU time
	CpuTime string `json:"cpuTime,omitempty"`
	// jobs run time
	RunTime string `json:"runTime,omitempty"`
	// run job id
	JobId string `json:"jobId,omitempty"`
	// job order date
	OrderDate string `json:"orderDate,omitempty"`
}
