/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type ZosTemplateData struct {
	// Template name HIDDEN
	Name string `json:"name,omitempty"`
	// Record format HIDDEN
	RecordFormat string `json:"recordFormat,omitempty"`
	// Logical record length HIDDEN
	LogicalRecordLength int32 `json:"logicalRecordLength,omitempty"`
	// Block Size HIDDEN
	BlockSize int32 `json:"blockSize,omitempty"`
	// Translation table HIDDEN
	TranslationTable string `json:"translationTable,omitempty"`
	// Transfer mode HIDDEN
	TransferMode string `json:"transferMode,omitempty"`
	// Management class HIDDEN
	SmsManagmentClass string `json:"smsManagmentClass,omitempty"`
	// Allocation units HIDDEN
	AllocationUnits string `json:"allocationUnits,omitempty"`
	// Volume HIDDEN
	Volume string `json:"volume,omitempty"`
	// Unit HIDDEN
	Unit string `json:"unit,omitempty"`
	// Primary Allocation HIDDEN
	PrimaryAllocation int32 `json:"primaryAllocation,omitempty"`
	// Secondary allocation HIDDEN
	SecondaryAllocation int32 `json:"secondaryAllocation,omitempty"`
	// Data class HIDDEN
	SmsDataClass string `json:"smsDataClass,omitempty"`
	// DBCS name HIDDEN
	DbcsEncoding string `json:"dbcsEncoding,omitempty"`
	// Transfer to unique file HIDDEN
	TransferToUniqueFile bool `json:"transferToUniqueFile,omitempty"`
	// Additional options host 1 HIDDEN
	AdditionalOptionsHost1 string `json:"additionalOptionsHost1,omitempty"`
	// Additional options host 1 HIDDEN
	AdditionalOptionsHost2 string `json:"additionalOptionsHost2,omitempty"`
}
