/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type Node struct {
	// Node Name
	Name string `json:"Name,omitempty"`
	// A unique id of the node
	Id string `json:"Id,omitempty"`
	Availability []Availability `json:"Availability,omitempty"`
	Performance []Performance `json:"Performance,omitempty"`
}
