/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

// File Transfer Server (FTS) configuration data
type FtsSettingsData struct {
	GeneralSettings *FtsGeneralSettings `json:"generalSettings,omitempty"`
	FtpSettings *FtsFtpSettings `json:"ftpSettings,omitempty"`
	SftpSettings *FtsSftpSettings `json:"sftpSettings,omitempty"`
	AuthenticationDetails *FtsAuthenticationDetails `json:"authenticationDetails,omitempty"`
}
