/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type HubData struct {
	// Hub state
	Status string `json:"status,omitempty"`
	// Hub sync status
	SyncStatus string `json:"syncStatus,omitempty"`
	// Agent name
	Name string `json:"name,omitempty"`
	// CPU
	Cpu string `json:"cpu,omitempty"`
	// memory usage
	Memory string `json:"memory,omitempty"`
	// Hub Health Message
	Message string `json:"message,omitempty"`
}
