/*
 * Control-M Services
 *
 * Provides access to BMC Control-M Services
 *
 * API version: 9.20.115
 * Contact: customer_support@bmc.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package controlm_go

type UpgradeAgentInfo struct {
	// Agent name.
	Agent string `json:"agent,omitempty"`
	// Control-M name.
	Ctm string `json:"ctm,omitempty"`
	// Agent type (Agent, MFT, AppPack).
	Type_ string `json:"type,omitempty"`
	// Platform.
	Platform string `json:"platform,omitempty"`
	// From version.
	FromVersion string `json:"fromVersion,omitempty"`
	// To version.
	ToVersion string `json:"toVersion,omitempty"`
}
